-- Migration 0004: FK constraints and senderId column
-- All changes were applied directly via webdev_execute_sql before this migration was generated.
-- This file is kept as a no-op to keep the drizzle journal in sync with the actual DB state.
--
-- Changes already applied to DB:
-- 1. ALTER TABLE `messages` ADD `senderId` int;
-- 2. ALTER TABLE `messages` ADD INDEX idx_messages_senderId (senderId);
-- 3. ALTER TABLE `messages` ADD CONSTRAINT fk_messages_sender FOREIGN KEY (senderId) REFERENCES users(id) ON DELETE SET NULL;
-- 4. ALTER TABLE `messages` ADD CONSTRAINT fk_messages_session FOREIGN KEY (sessionId) REFERENCES chat_sessions(id) ON DELETE CASCADE;
-- 5. ALTER TABLE `chat_sessions` ADD CONSTRAINT fk_sessions_operator FOREIGN KEY (operatorId) REFERENCES users(id) ON DELETE SET NULL;
-- 6. ALTER TABLE `surveys` ADD CONSTRAINT `surveys_sessionId_chat_sessions_id_fk` FOREIGN KEY (`sessionId`) REFERENCES `chat_sessions`(`id`) ON DELETE cascade ON UPDATE no action;
SELECT 1;
