/**
 * Cleanup Script — Remove test sessions generated by run_chat_simulation.mjs
 *
 * Deletes all chat_sessions and messages where visitorId starts with "test-bot-"
 */

import "dotenv/config";
import { createPool } from "mysql2/promise";

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) { console.error("DATABASE_URL not set"); process.exit(1); }

const pool = createPool(DATABASE_URL);

console.log("=".repeat(50));
console.log("  Cleanup: Removing test-bot sessions");
console.log("=".repeat(50));

// Count before deletion
const [[{ count: sessionCount }]] = await pool.query(
  "SELECT COUNT(*) as count FROM chat_sessions WHERE visitor_id LIKE 'test-bot-%'"
);
console.log(`  Found ${sessionCount} test sessions to delete`);

if (sessionCount === 0) {
  console.log("  Nothing to clean up.");
  await pool.end();
  process.exit(0);
}

// Delete messages first (foreign key constraint)
const [msgResult] = await pool.query(
  "DELETE m FROM messages m INNER JOIN chat_sessions cs ON m.session_id = cs.id WHERE cs.visitor_id LIKE 'test-bot-%'"
);
console.log(`  Deleted ${msgResult.affectedRows} messages`);

// Delete sessions
const [sessionResult] = await pool.query(
  "DELETE FROM chat_sessions WHERE visitor_id LIKE 'test-bot-%'"
);
console.log(`  Deleted ${sessionResult.affectedRows} sessions`);

console.log("  ✅ Cleanup complete");
console.log("=".repeat(50));

await pool.end();
